name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write   # 👈 gives Actions permission to push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: prathmeshrrai
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Push Snake to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
